//------------------------------------------------------------------------------
// <auto-generated>
//     Designer file for AccessAnalyzer.aspx.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.bussiness.production.admin.security
{
    public partial class AccessAnalyzer
    {
        protected global::System.Web.UI.WebControls.Label lbl_kpiPages;
        protected global::System.Web.UI.WebControls.Label lbl_kpiOverlay;
        protected global::System.Web.UI.WebControls.Label lbl_kpiConfig;
        protected global::System.Web.UI.WebControls.Label lbl_kpiHardcoded;
        protected global::System.Web.UI.WebControls.Label lbl_kpiModule;
        protected global::System.Web.UI.WebControls.Label lbl_kpiScanned;
        protected global::System.Web.UI.WebControls.RadioButtonList rbl_mode;
        protected global::System.Web.UI.WebControls.Button btn_csv;
        protected global::System.Web.UI.WebControls.Button btn_snapshot;
        protected global::System.Web.UI.WebControls.Button btn_print;
        protected global::System.Web.UI.WebControls.Label lbl_msg;
        protected global::System.Web.UI.WebControls.Panel pnl_permission;
        protected global::System.Web.UI.WebControls.DropDownList ddl_permission;
        protected global::System.Web.UI.WebControls.Button btn_analyzePermission;
        protected global::System.Web.UI.WebControls.Label lbl_permOverlay;
        protected global::System.Web.UI.WebControls.Label lbl_permConfig;
        protected global::System.Web.UI.WebControls.Label lbl_permHardcoded;
        protected global::System.Web.UI.WebControls.Label lbl_permModule;
        protected global::System.Web.UI.WebControls.GridView gv_permission;
        protected global::System.Web.UI.WebControls.Panel pnl_user;
        protected global::System.Web.UI.WebControls.TextBox txt_workman;
        protected global::System.Web.UI.WebControls.TextBox txt_firstname;
        protected global::System.Web.UI.WebControls.TextBox txt_fullname;
        protected global::System.Web.UI.WebControls.Button btn_searchUser;
        protected global::System.Web.UI.WebControls.GridView gv_userSearch;
        protected global::System.Web.UI.WebControls.Label lbl_userIdentity;
        protected global::System.Web.UI.WebControls.Label lbl_userGranted;
        protected global::System.Web.UI.WebControls.GridView gv_userPerms;
        protected global::System.Web.UI.WebControls.Panel pnl_legacy;
        protected global::System.Web.UI.WebControls.Button btn_analyzeLegacy;
        protected global::System.Web.UI.WebControls.GridView gv_legacy;
        protected global::System.Web.UI.WebControls.Panel pnl_overlay;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnl_overlayWarning;
        protected global::System.Web.UI.WebControls.Label lbl_overlayGrants;
        protected global::System.Web.UI.WebControls.Label lbl_overlayGroups;
        protected global::System.Web.UI.WebControls.Label lbl_overlayLegacyUsers;
        protected global::System.Web.UI.WebControls.GridView gv_direct;
        protected global::System.Web.UI.WebControls.GridView gv_groupGrants;
        protected global::System.Web.UI.WebControls.Label lbl_unused;
        protected global::System.Web.UI.WebControls.GridView gv_orphans;
        protected global::System.Web.UI.WebControls.Panel pnl_compare;
        protected global::System.Web.UI.WebControls.FileUpload fu_snapshotBefore;
        protected global::System.Web.UI.WebControls.FileUpload fu_snapshotAfter;
        protected global::System.Web.UI.WebControls.Button btn_compare;
        protected global::System.Web.UI.WebControls.Label lbl_compareVerdict;
        protected global::System.Web.UI.WebControls.GridView gv_compareMetrics;
        protected global::System.Web.UI.WebControls.GridView gv_compareChanges;
        protected global::System.Web.UI.WebControls.GridView gv_matrix;
    }
}
